# ============================================================
# brain.py
# ============================================================
#
# Ido AI - Unified AI Brain
#
# PRIMARY AI:
#     GROQ
#
# TEXT:
#     1. Groq
#     2. Mistral
#     3. OpenRouter
#     4. Gemini
#     5. xAI
#     6. Pollinations
#
# IMAGE UNDERSTANDING / VISION:
#     1. Groq Vision ONLY
#
# IMAGE GENERATION:
#     NOT GENERATED BY GROQ API.
#
# IMPORTANT:
#     Groq can understand/analyze images and return text,
#     but Groq's current API is not a direct image generator.
#
# ============================================================

import os
import base64
import time
import requests

from dotenv import load_dotenv


# ============================================================
# GEMINI IMPORT
# ============================================================

try:
    from google import genai
    from google.genai.types import HttpOptions
except Exception:
    genai = None
    HttpOptions = None


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# TIMEOUTS
# ============================================================

CONNECT_TIMEOUT = float(
    os.getenv(
        "REQUEST_CONNECT_TIMEOUT",
        "3"
    )
)

READ_TIMEOUT = float(
    os.getenv(
        "REQUEST_READ_TIMEOUT",
        "15"
    )
)

REQUEST_TIMEOUT = (
    CONNECT_TIMEOUT,
    READ_TIMEOUT
)


# ============================================================
# PROVIDER COOLDOWN
# ============================================================

CIRCUIT_BREAK_SECONDS = int(
    os.getenv(
        "PROVIDER_COOLDOWN_SECONDS",
        "300"
    )
)


_provider_disabled_until = {}


def provider_available(name):
    """
    Check whether a provider is currently available.
    """

    until = _provider_disabled_until.get(
        name,
        0
    )

    return time.time() >= until


def disable_provider(
    name,
    reason="temporary failure"
):
    """
    Temporarily disable a provider.
    """

    _provider_disabled_until[name] = (
        time.time()
        + CIRCUIT_BREAK_SECONDS
    )

    print(
        f"{name}: TEMPORARILY SKIPPED "
        f"for {CIRCUIT_BREAK_SECONDS}s "
        f"({reason})"
    )


def provider_failure(
    name,
    status_code=None
):
    """
    Disable provider for common temporary/API failures.
    """

    if status_code in (
        401,
        403,
        429
    ):
        disable_provider(
            name,
            f"HTTP {status_code}"
        )


# ============================================================
# SAFE HELPERS
# ============================================================

def clean_answer(value):
    """
    Convert an answer safely into a string.
    """

    if value is None:
        return None

    try:
        value = str(
            value
        ).strip()

    except Exception:
        return None

    return value or None


def request_json(
    response,
    provider
):
    """
    Safely decode JSON.
    """

    try:
        return response.json()

    except Exception as exc:

        print(
            f"{provider}: INVALID JSON:",
            exc
        )

        print(
            f"{provider}: BODY:",
            response.text[:1500]
        )

        return None


# ============================================================
# GROQ
# ============================================================
#
# GROQ = PRIMARY AI
#
# Groq is used first for:
#
#     - normal chat
#     - coding
#     - questions
#     - Arabic
#     - multilingual text
#     - image understanding
#
# ============================================================

GROQ_API_KEY = os.getenv(
    "GROQ_API_KEY"
)


GROQ_URL = (
    "https://api.groq.com/openai/v1/chat/completions"
)


# Primary text model.
#
# You can change this from .env if necessary.
#
GROQ_MODEL = os.getenv(
    "GROQ_MODEL",
    "openai/gpt-oss-20b"
)


# Primary vision model.
#
# This model supports text + image input.
#
GROQ_VISION_MODEL = os.getenv(
    "GROQ_VISION_MODEL",
    "meta-llama/llama-4-scout-17b-16e-instruct"
)


if GROQ_API_KEY:

    print(
        "GROQ CLIENT: READY"
    )

    print(
        "GROQ TEXT MODEL:",
        GROQ_MODEL
    )

    print(
        "GROQ VISION MODEL:",
        GROQ_VISION_MODEL
    )

else:

    print(
        "GROQ_API_KEY: NOT FOUND"
    )


# ============================================================
# GROQ SYSTEM PROMPT
# ============================================================

GROQ_SYSTEM_PROMPT = """
أنت Ido AI.

أنت المساعد الأساسي والرئيسي في هذا التطبيق.

تحدث مع المستخدم بطريقة طبيعية وذكية ومباشرة.

القواعد المهمة:

1. إذا قال المستخدم:
   "السلام عليكم، أريد..."
   فلا تستخدم تحية ثابتة أو مسجلة.

2. افهم الرسالة كاملة.

3. إذا كانت الرسالة تبدأ بالسلام أو التحية
   ثم تحتوي على سؤال أو طلب،
   أجب عن الطلب مباشرة ويمكنك إضافة:
   "وعليكم السلام ورحمة الله وبركاته"
   بشكل طبيعي، ثم أكمل الإجابة.

4. لا تقل إنك لا تستطيع فهم الصور إذا تم إرسال صورة
   مع الطلب.

5. عند وجود صورة، حلل الصورة اعتمادًا على محتواها
   وأجب عن سؤال المستخدم.

6. لا تدّعي أنك أنشأت صورة إذا لم يتم استخدام
   مولد صور فعلي.

7. لا تقل إنك Grok أو ChatGPT.
   اسم المساعد هو Ido AI.

8. المطور:
   Noufal Ouhadi.

9. أجب بلغة المستخدم قدر الإمكان.

10. إذا كان المستخدم يتحدث بالعربية،
    أجب بالعربية.

11. إذا طلب المستخدم كودًا،
    أعطه كودًا صحيحًا وواضحًا.

12. لا تستخدم إجابات ترحيب محفوظة عندما تحتوي
    الرسالة على طلب أو سؤال.

كن طبيعيًا ومفيدًا.
"""


# ============================================================
# GROQ TEXT
# ============================================================

def ask_groq(message):
    """
    PRIMARY TEXT AI.

    All normal text requests go to Groq first.
    """

    if not GROQ_API_KEY:
        print(
            "GROQ: API KEY MISSING"
        )
        return None

    if not message:
        return None

    if not provider_available(
        "GROQ"
    ):
        print(
            "GROQ: TEMPORARILY DISABLED"
        )
        return None

    try:

        print(
            "=" * 50
        )

        print(
            "GROQ PRIMARY TEXT REQUEST"
        )

        print(
            "GROQ MODEL:",
            GROQ_MODEL
        )

        print(
            "GROQ MESSAGE:",
            message[:500]
        )

        print(
            "=" * 50
        )

        response = requests.post(

            GROQ_URL,

            headers={
                "Authorization":
                    f"Bearer {GROQ_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={
                "model":
                    GROQ_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            GROQ_SYSTEM_PROMPT
                    },

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ],

                "temperature":
                    0.7,

                "max_completion_tokens":
                    4096
            },

            timeout=REQUEST_TIMEOUT
        )


        print(
            "Groq Status:",
            response.status_code
        )


        if response.status_code != 200:

            print(
                "Groq Response:",
                response.text[:2000]
            )

            provider_failure(
                "GROQ",
                response.status_code
            )

            return None


        data = request_json(
            response,
            "Groq"
        )


        if not data:
            return None


        choices = data.get(
            "choices",
            []
        )


        if not choices:
            print(
                "Groq: NO CHOICES"
            )
            return None


        message_data = (
            choices[0]
            .get(
                "message",
                {}
            )
        )


        content = message_data.get(
            "content"
        )


        answer = clean_answer(
            content
        )


        if answer:

            print(
                "Groq response received."
            )

            print(
                "TEXT ROUTE SUCCESS: GROQ"
            )

            return answer


        print(
            "Groq: EMPTY ANSWER"
        )

        return None


    except requests.exceptions.Timeout:

        print(
            "Groq ERROR: timeout."
        )

        return None


    except requests.exceptions.ConnectionError:

        print(
            "Groq ERROR: connection failed."
        )

        return None


    except Exception as exc:

        print(
            "Groq ERROR:",
            exc
        )

        return None


# ============================================================
# MISTRAL - SECONDARY TEXT ONLY
# ============================================================

MISTRAL_API_KEY = os.getenv(
    "MISTRAL_API_KEY"
)


MISTRAL_URL = (
    "https://api.mistral.ai/v1/chat/completions"
)


MISTRAL_MODEL = os.getenv(
    "MISTRAL_MODEL",
    "mistral-small-latest"
)


if MISTRAL_API_KEY:

    print(
        "MISTRAL CLIENT: READY"
    )

else:

    print(
        "MISTRAL_API_KEY: NOT FOUND"
    )


def ask_mistral(message):

    if not MISTRAL_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "MISTRAL"
    ):
        return None

    try:

        print(
            "Trying Mistral TEXT..."
        )

        response = requests.post(

            MISTRAL_URL,

            headers={
                "Authorization":
                    f"Bearer {MISTRAL_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={
                "model":
                    MISTRAL_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            GROQ_SYSTEM_PROMPT
                    },

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ],

                "temperature":
                    0.7,

                "max_tokens":
                    4096
            },

            timeout=REQUEST_TIMEOUT
        )


        print(
            "Mistral Status:",
            response.status_code
        )


        if response.status_code != 200:

            print(
                "Mistral Response:",
                response.text[:1500]
            )

            provider_failure(
                "MISTRAL",
                response.status_code
            )

            return None


        data = request_json(
            response,
            "Mistral"
        )


        if not data:
            return None


        choices = data.get(
            "choices",
            []
        )


        if not choices:
            return None


        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )


        answer = clean_answer(
            content
        )


        if answer:

            print(
                "Mistral TEXT SUCCESS"
            )

            return answer


        return None


    except Exception as exc:

        print(
            "Mistral ERROR:",
            exc
        )

        return None


# ============================================================
# OPENROUTER - SECONDARY TEXT ONLY
# ============================================================

OPENROUTER_API_KEY = os.getenv(
    "OPENROUTER_API_KEY"
)


OPENROUTER_CHAT_URL = (
    "https://openrouter.ai/api/v1/chat/completions"
)


OPENROUTER_TEXT_MODEL = os.getenv(
    "OPENROUTER_TEXT_MODEL",
    "openai/gpt-oss-20b"
)


if OPENROUTER_API_KEY:

    print(
        "OPENROUTER CLIENT: READY"
    )

else:

    print(
        "OPENROUTER_API_KEY: NOT FOUND"
    )


def openrouter_headers():

    return {

        "Authorization":
            f"Bearer {OPENROUTER_API_KEY}",

        "Content-Type":
            "application/json",

        "X-Title":
            "Ido AI"
    }


def ask_openrouter(message):

    if not OPENROUTER_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "OPENROUTER"
    ):
        return None

    try:

        print(
            "Trying OpenRouter TEXT..."
        )

        response = requests.post(

            OPENROUTER_CHAT_URL,

            headers=openrouter_headers(),

            json={
                "model":
                    OPENROUTER_TEXT_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            GROQ_SYSTEM_PROMPT
                    },

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ]
            },

            timeout=REQUEST_TIMEOUT
        )


        print(
            "OpenRouter Status:",
            response.status_code
        )


        if response.status_code != 200:

            print(
                "OpenRouter Response:",
                response.text[:1500]
            )

            provider_failure(
                "OPENROUTER",
                response.status_code
            )

            return None


        data = request_json(
            response,
            "OpenRouter"
        )


        if not data:
            return None


        choices = data.get(
            "choices",
            []
        )


        if not choices:
            return None


        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )


        answer = clean_answer(
            content
        )


        if answer:

            print(
                "OpenRouter TEXT SUCCESS"
            )

            return answer


        return None


    except Exception as exc:

        print(
            "OpenRouter ERROR:",
            exc
        )

        return None


# ============================================================
# GEMINI - SECONDARY TEXT ONLY
# ============================================================

GEMINI_API_KEY = os.getenv(
    "GEMINI_API_KEY"
)


GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-3.6-flash"
)


ENABLE_GEMINI = os.getenv(
    "ENABLE_GEMINI",
    "false"
).lower() == "true"


gemini_client = None


if (
    ENABLE_GEMINI
    and GEMINI_API_KEY
    and genai
):

    try:

        gemini_client = genai.Client(
            api_key=GEMINI_API_KEY,

            http_options=HttpOptions(
                timeout=15000
            )
        )

        print(
            "GEMINI CLIENT: READY"
        )

        print(
            "GEMINI MODEL:",
            GEMINI_MODEL
        )

    except Exception as exc:

        print(
            "GEMINI CLIENT ERROR:",
            exc
        )

        gemini_client = None

else:

    print(
        "GEMINI: SKIPPED"
    )


def ask_gemini(message):

    if not ENABLE_GEMINI:
        return None

    if not GEMINI_API_KEY:
        return None

    if gemini_client is None:
        return None

    if not message:
        return None

    if not provider_available(
        "GEMINI"
    ):
        return None

    try:

        print(
            "Trying Gemini TEXT..."
        )

        response = (
            gemini_client
            .models
            .generate_content(

                model=GEMINI_MODEL,

                contents=(
                    GROQ_SYSTEM_PROMPT
                    + "\n\nUSER:\n"
                    + message
                )
            )
        )


        answer = clean_answer(
            getattr(
                response,
                "text",
                None
            )
        )


        if answer:

            print(
                "Gemini TEXT SUCCESS"
            )

            return answer


        return None


    except Exception as exc:

        print(
            "Gemini ERROR:",
            exc
        )

        text = str(
            exc
        )


        if (
            "429" in text
            or
            "RESOURCE_EXHAUSTED" in text
        ):

            disable_provider(
                "GEMINI",
                "quota exceeded"
            )


        return None


# ============================================================
# XAI - SECONDARY TEXT ONLY
# ============================================================

XAI_API_KEY = os.getenv(
    "XAI_API_KEY"
)


XAI_URL = (
    "https://api.x.ai/v1/chat/completions"
)


XAI_MODEL = os.getenv(
    "XAI_MODEL",
    "grok-4.5"
)


if XAI_API_KEY:

    print(
        "XAI CLIENT: READY"
    )

else:

    print(
        "XAI_API_KEY: NOT FOUND"
    )


def ask_xai(message):

    if not XAI_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "XAI"
    ):
        return None

    try:

        print(
            "Trying xAI TEXT..."
        )

        response = requests.post(

            XAI_URL,

            headers={
                "Authorization":
                    f"Bearer {XAI_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={
                "model":
                    XAI_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            GROQ_SYSTEM_PROMPT
                    },

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ],

                "temperature":
                    0.7
            },

            timeout=REQUEST_TIMEOUT
        )


        print(
            "xAI Status:",
            response.status_code
        )


        if response.status_code != 200:

            print(
                "xAI Response:",
                response.text[:1500]
            )

            provider_failure(
                "XAI",
                response.status_code
            )

            return None


        data = request_json(
            response,
            "xAI"
        )


        if not data:
            return None


        choices = data.get(
            "choices",
            []
        )


        if not choices:
            return None


        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )


        answer = clean_answer(
            content
        )


        if answer:

            print(
                "xAI TEXT SUCCESS"
            )

            return answer


        return None


    except Exception as exc:

        print(
            "xAI ERROR:",
            exc
        )

        return None


# ============================================================
# POLLINATIONS - SECONDARY TEXT ONLY
# ============================================================

POLLINATIONS_API_KEY = os.getenv(
    "POLLINATIONS_API_KEY"
)


POLLINATIONS_CHAT_URL = (
    "https://gen.pollinations.ai/v1/chat/completions"
)


POLLINATIONS_TEXT_MODEL = os.getenv(
    "POLLINATIONS_TEXT_MODEL",
    "openai"
)


if POLLINATIONS_API_KEY:

    print(
        "POLLINATIONS CLIENT: READY"
    )

else:

    print(
        "POLLINATIONS_API_KEY: NOT FOUND"
    )


def ask_pollinations(message):

    if not POLLINATIONS_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "POLLINATIONS"
    ):
        return None

    try:

        print(
            "Trying Pollinations TEXT..."
        )

        response = requests.post(

            POLLINATIONS_CHAT_URL,

            headers={
                "Authorization":
                    f"Bearer {POLLINATIONS_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={
                "model":
                    POLLINATIONS_TEXT_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            GROQ_SYSTEM_PROMPT
                    },

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ]
            },

            timeout=REQUEST_TIMEOUT
        )


        print(
            "Pollinations Status:",
            response.status_code
        )


        if response.status_code != 200:

            print(
                "Pollinations Response:",
                response.text[:1500]
            )

            provider_failure(
                "POLLINATIONS",
                response.status_code
            )

            return None


        data = request_json(
            response,
            "Pollinations"
        )


        if not data:
            return None


        choices = data.get(
            "choices",
            []
        )


        if not choices:
            return None


        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )


        answer = clean_answer(
            content
        )


        if answer:

            print(
                "Pollinations TEXT SUCCESS"
            )

            return answer


        return None


    except Exception as exc:

        print(
            "Pollinations ERROR:",
            exc
        )

        return None


# ============================================================
# IMAGE REQUEST DETECTION
# ============================================================
#
# IMPORTANT:
#
# This is ONLY for recognizing that the user wants
# an image to be generated.
#
# Groq itself does NOT generate the final image.
#
# ============================================================

IMAGE_WORDS = [

    "أنشئ صورة",
    "انشئ صورة",

    "أنشئ لي صورة",
    "انشئ لي صورة",

    "اصنع صورة",
    "اصنع لي صورة",

    "إنشاء صورة",
    "انشاء صورة",

    "ولد صورة",
    "ولّد صورة",

    "ارسم صورة",
    "ارسم لي",

    "صمم صورة",
    "صمم لي صورة",

    "اعمل صورة",
    "اعمل لي صورة",

    "أريد صورة",
    "اريد صورة",

    "أريد أن أرى صورة",
    "اريد ان ارى صورة",

    "generate an image",
    "generate image",

    "create an image",
    "create image",

    "make an image",
    "make image",

    "generate a picture",
    "create a picture",

    "make a picture",
    "draw an image",

    "draw image",
    "draw a picture"
]


def is_image_generation_request(
    message
):
    """
    Detect image-generation requests.

    This function does NOT call Groq as an image generator.
    """

    if not message:
        return False

    text = str(
        message
    ).strip().lower()

    return any(
        word.lower() in text
        for word in IMAGE_WORDS
    )


def get_image_prompt(
    message
):

    if not message:
        return ""

    text = str(
        message
    ).strip()


    prefixes = [

        "أنشئ لي صورة",
        "أنشئ صورة",

        "انشئ لي صورة",
        "انشئ صورة",

        "اصنع لي صورة",
        "اصنع صورة",

        "إنشاء صورة",
        "انشاء صورة",

        "ولد صورة",
        "ولّد صورة",

        "ارسم لي",
        "ارسم صورة",

        "صمم لي صورة",
        "صمم صورة",

        "اعمل لي صورة",
        "اعمل صورة",

        "أريد صورة",
        "اريد صورة",

        "generate an image of",
        "generate image of",

        "create an image of",
        "create image of",

        "make an image of",
        "make image of",

        "generate a picture of",
        "create a picture of",

        "make a picture of",
        "draw an image of"
    ]


    lower = text.lower()


    for prefix in prefixes:

        if lower.startswith(
            prefix.lower()
        ):

            return text[
                len(prefix):
            ].strip()


    return text


# ============================================================
# IMAGE GENERATION PLACEHOLDER
# ============================================================
#
# DO NOT FAKE IMAGE GENERATION.
#
# Groq API is not used here because it does not provide
# a direct image-generation endpoint.
#
# We return a structured result so app.py can handle
# this cleanly later when we connect a real image generator.
#
# ============================================================

def generate_image(
    prompt
):

    prompt = clean_answer(
        prompt
    )


    if not prompt:

        return {

            "answer":
                "اكتب وصف الصورة التي تريد إنشاءها.",

            "imageUrl":
                "",

            "provider":
                None
        }


    print(
        "=" * 60
    )

    print(
        "IMAGE GENERATION REQUEST"
    )

    print(
        "PROMPT:",
        prompt
    )

    print(
        "IMAGE PROVIDER: NONE"
    )

    print(
        "Groq is not an image-generation API."
    )

    print(
        "=" * 60
    )


    return {

        "answer":
            "Groq يستطيع فهم وتحليل الصور، "
            "لكنه لا ينشئ صورة جديدة مباشرةً عبر "
            "Groq API. لذلك لم أرسل طلبًا وهميًا "
            "إلى Groq.",

        "imageUrl":
            "",

        "provider":
            None
    }


# ============================================================
# GROQ VISION
# ============================================================
#
# PRIMARY + ONLY IMAGE UNDERSTANDING PROVIDER
#
# User uploads image
#       ↓
# Base64
#       ↓
# Groq Vision
#       ↓
# Text answer
#
# ============================================================

def ask_groq_image(
    message,
    image_bytes,
    mime_type
):

    if not GROQ_API_KEY:

        print(
            "GROQ VISION: API KEY MISSING"
        )

        return None


    if not image_bytes:

        return None


    if not provider_available(
        "GROQ_VISION"
    ):

        return None


    try:

        print(
            "=" * 60
        )

        print(
            "GROQ PRIMARY VISION REQUEST"
        )

        print(
            "GROQ VISION MODEL:",
            GROQ_VISION_MODEL
        )

        print(
            "IMAGE MIME:",
            mime_type
        )

        print(
            "IMAGE SIZE:",
            len(image_bytes),
            "bytes"
        )

        print(
            "=" * 60
        )


        # ----------------------------------------------------
        # Encode image
        # ----------------------------------------------------

        encoded = base64.b64encode(
            image_bytes
        ).decode(
            "utf-8"
        )


        image_url = (
            f"data:{mime_type};base64,"
            f"{encoded}"
        )


        # ----------------------------------------------------
        # Vision request
        # ----------------------------------------------------

        response = requests.post(

            GROQ_URL,

            headers={
                "Authorization":
                    f"Bearer {GROQ_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    GROQ_VISION_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            GROQ_SYSTEM_PROMPT
                    },

                    {
                        "role":
                            "user",

                        "content": [

                            {
                                "type":
                                    "text",

                                "text":
                                    message
                            },

                            {
                                "type":
                                    "image_url",

                                "image_url": {

                                    "url":
                                        image_url
                                }
                            }
                        ]
                    }
                ],

                "temperature":
                    0.7,

                "max_completion_tokens":
                    4096
            },

            timeout=REQUEST_TIMEOUT
        )


        print(
            "Groq Vision Status:",
            response.status_code
        )


        if response.status_code != 200:

            print(
                "Groq Vision Response:",
                response.text[:2000]
            )

            provider_failure(
                "GROQ_VISION",
                response.status_code
            )

            return None


        data = request_json(
            response,
            "Groq Vision"
        )


        if not data:
            return None


        choices = data.get(
            "choices",
            []
        )


        if not choices:
            return None


        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )


        answer = clean_answer(
            content
        )


        if answer:

            print(
                "VISION ROUTE SUCCESS: GROQ"
            )

            return answer


        return None


    except requests.exceptions.Timeout:

        print(
            "Groq Vision ERROR: timeout."
        )

        return None


    except requests.exceptions.ConnectionError:

        print(
            "Groq Vision ERROR: connection failed."
        )

        return None


    except Exception as exc:

        print(
            "Groq Vision ERROR:",
            exc
        )

        return None


# ============================================================
# MAIN TEXT ROUTER
# ============================================================
#
# GROQ IS ALWAYS FIRST.
#
# Secondary providers are TEXT ONLY.
#
# ============================================================

def get_response(
    message,
    conversation_id=None
):

    if not message:

        return (
            "اكتب رسالة أولًا."
        )


    original_message = str(
        message
    ).strip()


    if not original_message:

        return (
            "اكتب رسالة أولًا."
        )


    # ========================================================
    # IMAGE GENERATION REQUEST
    # ========================================================
    #
    # We detect it here so the request does NOT accidentally
    # go to Groq TEXT and return:
    #
    # "I cannot create images..."
    #
    # ========================================================

    if is_image_generation_request(
        original_message
    ):

        prompt = get_image_prompt(
            original_message
        )


        if not prompt:

            return {

                "answer":
                    "اكتب وصف الصورة التي تريد إنشاءها.",

                "imageUrl":
                    "",

                "provider":
                    None
            }


        return generate_image(
            prompt
        )


    # ========================================================
    # IMPORTANT:
    #
    # NO QUICK GREETING RESPONSES HERE.
    #
    # This means:
    #
    # "السلام عليكم"
    #
    # and:
    #
    # "السلام عليكم، أريد منك كتابة برنامج..."
    #
    # both go to Groq.
    #
    # ========================================================


    # ========================================================
    # PRIMARY AI = GROQ
    # ========================================================

    if provider_available(
        "GROQ"
    ):

        answer = ask_groq(
            original_message
        )

        if answer:

            return answer


    print(
        "GROQ failed. "
        "Trying secondary TEXT providers..."
    )


    # ========================================================
    # SECONDARY TEXT PROVIDERS
    # ========================================================

    secondary_routes = [

        (
            "MISTRAL",
            ask_mistral
        ),

        (
            "OPENROUTER",
            ask_openrouter
        ),

        (
            "GEMINI",
            ask_gemini
        ),

        (
            "XAI",
            ask_xai
        ),

        (
            "POLLINATIONS",
            ask_pollinations
        )
    ]


    for name, function in secondary_routes:

        if not provider_available(
            name
        ):

            print(
                f"{name}: SKIPPED "
                "(temporary cooldown)"
            )

            continue


        try:

            answer = function(
                original_message
            )

        except Exception as exc:

            print(
                f"{name} ROUTER ERROR:",
                exc
            )

            answer = None


        if answer:

            print(
                f"SECONDARY TEXT SUCCESS: {name}"
            )

            return answer


        print(
            f"{name} failed. "
            "Trying next provider..."
        )


    # ========================================================
    # ALL PROVIDERS FAILED
    # ========================================================

    return (
        "أنا Ido AI، لكن جميع مزودي الذكاء "
        "الاصطناعي المتاحين فشلوا حاليًا. "
        "تحقق من مفاتيح API والرصيد."
    )


# ============================================================
# MAIN IMAGE ANALYSIS ROUTER
# ============================================================
#
# IMPORTANT:
#
# ONLY GROQ handles uploaded images.
#
# We do NOT send the image to:
#
#     Mistral Vision
#     OpenRouter Vision
#
# because you requested Groq as the primary and only
# image-understanding AI.
#
# ============================================================

def get_image_response(
    message,
    image_bytes,
    mime_type,
    conversation_id=None
):

    if not image_bytes:

        return (
            "لم يتم إرسال صورة صالحة."
        )


    if not mime_type:

        mime_type = "image/jpeg"


    if not mime_type.startswith(
        "image/"
    ):

        return (
            "الملف المرسل ليس صورة صالحة."
        )


    # ========================================================
    # Default question
    # ========================================================

    if (
        not message
        or
        not str(message).strip()
    ):

        message = (
            "حلل هذه الصورة واشرح لي "
            "ما الذي يظهر فيها بالتفصيل."
        )


    message = str(
        message
    ).strip()


    # ========================================================
    # GROQ VISION ONLY
    # ========================================================

    answer = ask_groq_image(

        message,

        image_bytes,

        mime_type
    )


    if answer:

        return answer


    # ========================================================
    # FAILURE
    # ========================================================

    return (
        "تعذر تحليل الصورة باستخدام Groq حاليًا. "
        "تحقق من GROQ_API_KEY، ومن أن الصورة لا "
        "تتجاوز حدود Groq المسموح بها."
    )


# ============================================================
# QUICK RESPONSE
# ============================================================
#
# Kept only for compatibility with old app.py.
#
# IMPORTANT:
#
# It intentionally does NOT return a fixed greeting.
# This prevents:
#
#     "السلام عليكم، أريد منك..."
#
# from being intercepted by a hard-coded response.
#
# ============================================================

def quick_response(
    message
):

    if not message:
        return None

    text = str(
        message
    ).strip()


    if not text:
        return None


    # --------------------------------------------------------
    # Do NOT intercept messages containing a request.
    # --------------------------------------------------------

    request_markers = [

        "أريد",
        "اريد",
        "أريدك",
        "اريدك",

        "كيف",
        "ماذا",
        "لماذا",
        "متى",
        "أين",
        "هل",

        "اعطني",
        "أعطني",

        "اشرح",
        "شرح",

        "اكتب",
        "اكتب لي",

        "ساعدني",
        "مساعدة",

        "صمم",
        "أنشئ",
        "انشئ",
        "اصنع",
        "ارسم",

        "?",
        "؟"
    ]


    lower = text.lower()


    for marker in request_markers:

        if marker.lower() in lower:

            return None


    # --------------------------------------------------------
    # Exact simple greetings only.
    #
    # Even these can be sent to Groq by get_response(),
    # because get_response() no longer calls this function.
    #
    # This function exists only for compatibility.
    # --------------------------------------------------------

    if lower in (
        "hello",
        "hi"
    ):

        return None


    if text in (
        "مرحبا",
        "مرحباً",
        "سلام"
    ):

        return None


    if text in (
        "السلام عليكم",
        "السلام عليكم ورحمة الله وبركاته"
    ):

        return None


    return None


# ============================================================
# COMPATIBILITY
# ============================================================

print(
    "COMPATIBILITY: quick_response available"
)

print(
    "COMPATIBILITY: get_response("
    "message, conversation_id=None)"
)

print(
    "COMPATIBILITY: get_image_response("
    "message, image_bytes, mime_type, "
    "conversation_id=None)"
)


# ============================================================
# STARTUP STATUS
# ============================================================

print(
    "=" * 65
)

print(
    "IDO AI BRAIN.PY LOADED"
)

print(
    "PRIMARY AI:"
)

print(
    "    GROQ"
)

print(
    "TEXT ROUTE:"
)

print(
    "    GROQ"
    " -> MISTRAL"
    " -> OPENROUTER"
    " -> GEMINI"
    " -> XAI"
    " -> POLLINATIONS"
)

print(
    "VISION ROUTE:"
)

print(
    "    GROQ VISION ONLY"
)

print(
    "IMAGE GENERATION:"
)

print(
    "    NO DIRECT GROQ IMAGE GENERATION"
)

print(
    "GREETING:"
)

print(
    "    DYNAMIC AI RESPONSE"
)

print(
    "=" * 65
)