# ============================================================
# Ido AI - Unified Brain
# ============================================================
#
# PRIMARY AI:
#     GROQ
#
# TEXT:
#     GROQ
#     -> MISTRAL
#     -> OPENROUTER
#     -> GEMINI
#     -> XAI
#     -> POLLINATIONS
#
# IMAGE UNDERSTANDING:
#     GROQ VISION
#     -> OPENROUTER VISION
#     -> MISTRAL VISION
#
# IMAGE GENERATION:
#     GROQ understands the request,
#     but Groq API itself does NOT generate images.
#     The request is therefore sent to a real image provider.
#
# IMPORTANT:
#     Groq is always the FIRST AI for normal text.
#     Groq Vision is always the FIRST AI for image analysis.
#
# ============================================================

import os
import base64
import time
import requests

from dotenv import load_dotenv

load_dotenv()


# ============================================================
# CONFIGURATION
# ============================================================

CONNECT_TIMEOUT = float(
    os.getenv(
        "REQUEST_CONNECT_TIMEOUT",
        "5"
    )
)

READ_TIMEOUT = float(
    os.getenv(
        "REQUEST_READ_TIMEOUT",
        "30"
    )
)

REQUEST_TIMEOUT = (
    CONNECT_TIMEOUT,
    READ_TIMEOUT
)

CIRCUIT_BREAK_SECONDS = int(
    os.getenv(
        "PROVIDER_COOLDOWN_SECONDS",
        "300"
    )
)

_provider_disabled_until = {}


# ============================================================
# PROVIDER CONTROL
# ============================================================

def provider_available(name):

    until = _provider_disabled_until.get(
        name,
        0
    )

    return time.time() >= until


def disable_provider(
    name,
    reason="temporary failure"
):

    _provider_disabled_until[name] = (
        time.time()
        + CIRCUIT_BREAK_SECONDS
    )

    print(
        f"{name}: TEMPORARILY DISABLED "
        f"for {CIRCUIT_BREAK_SECONDS}s "
        f"({reason})"
    )


def provider_failure(
    name,
    status_code=None
):

    if status_code in (
        401,
        403,
        429
    ):

        disable_provider(
            name,
            f"HTTP {status_code}"
        )


# ============================================================
# HELPERS
# ============================================================

def clean_answer(value):

    if value is None:
        return None

    try:
        value = str(value).strip()

    except Exception:
        return None

    return value or None


def request_json(
    response,
    provider
):

    try:

        return response.json()

    except Exception as exc:

        print(
            f"{provider}: INVALID JSON:",
            exc
        )

        print(
            f"{provider}: BODY:",
            response.text[:1500]
        )

        return None


# ============================================================
# GROQ - PRIMARY AI
# ============================================================

GROQ_API_KEY = os.getenv(
    "GROQ_API_KEY"
)

GROQ_URL = (
    "https://api.groq.com/openai/v1/chat/completions"
)

GROQ_MODEL = os.getenv(
    "GROQ_MODEL",
    "openai/gpt-oss-20b"
)

GROQ_VISION_MODEL = os.getenv(
    "GROQ_VISION_MODEL",
    "qwen/qwen3.6-27b"
)


if GROQ_API_KEY:

    print(
        "GROQ CLIENT: READY"
    )

    print(
        "GROQ TEXT MODEL:",
        GROQ_MODEL
    )

    print(
        "GROQ VISION MODEL:",
        GROQ_VISION_MODEL
    )

else:

    print(
        "GROQ_API_KEY: NOT FOUND"
    )


# ============================================================
# GROQ TEXT
# ============================================================

def ask_groq(message):

    if not GROQ_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "GROQ"
    ):
        return None

    try:

        print(
            "Trying PRIMARY AI: Groq..."
        )

        system_prompt = """
You are Ido AI.

You are the primary AI assistant.

Always answer the user's actual request.

If the user begins with a greeting such as:
السلام عليكم
مرحبا
سلام
hello
hi

and then asks a real question or gives a real request,
do NOT stop at the greeting.

Reply naturally to the greeting first and then answer
the actual request.

Example:

User:
السلام عليكم، ما هي عاصمة المغرب؟

Good:
وعليكم السلام ورحمة الله وبركاته.
عاصمة المغرب هي الرباط.

Bad:
وعليكم السلام، كيف يمكنني مساعدتك؟

Never replace a real request with a generic greeting.

You are multilingual and should normally answer
in the same language used by the user.

Do not claim that you generated an image if no image
was actually generated by the application.
"""

        response = requests.post(

            GROQ_URL,

            headers={
                "Authorization":
                    f"Bearer {GROQ_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    GROQ_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            system_prompt
                    },

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ],

                "temperature":
                    0.7,

                "max_completion_tokens":
                    2048
            },

            timeout=REQUEST_TIMEOUT
        )

        print(
            "Groq Status:",
            response.status_code
        )

        if response.status_code != 200:

            print(
                "Groq Response:",
                response.text[:1500]
            )

            provider_failure(
                "GROQ",
                response.status_code
            )

            return None

        data = request_json(
            response,
            "Groq"
        )

        if not data:
            return None

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            return None

        message_data = (
            choices[0].get(
                "message",
                {}
            )
        )

        content = message_data.get(
            "content"
        )

        answer = clean_answer(
            content
        )

        if answer:

            print(
                "PRIMARY AI SUCCESS: GROQ"
            )

            return answer

        return None

    except requests.exceptions.Timeout:

        print(
            "Groq ERROR: timeout."
        )

        return None

    except requests.exceptions.ConnectionError:

        print(
            "Groq ERROR: connection failed."
        )

        return None

    except Exception as exc:

        print(
            "Groq ERROR:",
            exc
        )

        return None


# ============================================================
# MISTRAL - TEXT FALLBACK
# ============================================================

MISTRAL_API_KEY = os.getenv(
    "MISTRAL_API_KEY"
)

MISTRAL_URL = (
    "https://api.mistral.ai/v1/chat/completions"
)

MISTRAL_MODEL = os.getenv(
    "MISTRAL_MODEL",
    "mistral-small-latest"
)


def ask_mistral(message):

    if not MISTRAL_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "MISTRAL"
    ):
        return None

    try:

        print(
            "Trying fallback: Mistral..."
        )

        response = requests.post(

            MISTRAL_URL,

            headers={
                "Authorization":
                    f"Bearer {MISTRAL_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    MISTRAL_MODEL,

                "messages": [

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ],

                "temperature":
                    0.7,

                "max_tokens":
                    2048
            },

            timeout=REQUEST_TIMEOUT
        )

        print(
            "Mistral Status:",
            response.status_code
        )

        if response.status_code != 200:

            provider_failure(
                "MISTRAL",
                response.status_code
            )

            return None

        data = request_json(
            response,
            "Mistral"
        )

        if not data:
            return None

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            return None

        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )

        return clean_answer(
            content
        )

    except Exception as exc:

        print(
            "Mistral ERROR:",
            exc
        )

        return None


# ============================================================
# OPENROUTER - TEXT FALLBACK
# ============================================================

OPENROUTER_API_KEY = os.getenv(
    "OPENROUTER_API_KEY"
)

OPENROUTER_CHAT_URL = (
    "https://openrouter.ai/api/v1/chat/completions"
)

OPENROUTER_TEXT_MODEL = os.getenv(
    "OPENROUTER_TEXT_MODEL",
    "openai/gpt-oss-20b"
)


def openrouter_headers():

    return {

        "Authorization":
            f"Bearer {OPENROUTER_API_KEY}",

        "Content-Type":
            "application/json",

        "X-Title":
            "Ido AI"
    }


def ask_openrouter(message):

    if not OPENROUTER_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "OPENROUTER"
    ):
        return None

    try:

        print(
            "Trying fallback: OpenRouter..."
        )

        response = requests.post(

            OPENROUTER_CHAT_URL,

            headers=openrouter_headers(),

            json={

                "model":
                    OPENROUTER_TEXT_MODEL,

                "messages": [

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ]
            },

            timeout=REQUEST_TIMEOUT
        )

        print(
            "OpenRouter Status:",
            response.status_code
        )

        if response.status_code != 200:

            provider_failure(
                "OPENROUTER",
                response.status_code
            )

            return None

        data = request_json(
            response,
            "OpenRouter"
        )

        if not data:
            return None

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            return None

        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )

        return clean_answer(
            content
        )

    except Exception as exc:

        print(
            "OpenRouter ERROR:",
            exc
        )

        return None


# ============================================================
# XAI - TEXT FALLBACK
# ============================================================

XAI_API_KEY = os.getenv(
    "XAI_API_KEY"
)

XAI_URL = (
    "https://api.x.ai/v1/chat/completions"
)

XAI_MODEL = os.getenv(
    "XAI_MODEL",
    "grok-4.5"
)


def ask_xai(message):

    if not XAI_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "XAI"
    ):
        return None

    try:

        print(
            "Trying fallback: xAI..."
        )

        response = requests.post(

            XAI_URL,

            headers={
                "Authorization":
                    f"Bearer {XAI_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    XAI_MODEL,

                "messages": [

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ],

                "temperature":
                    0.7
            },

            timeout=REQUEST_TIMEOUT
        )

        if response.status_code != 200:

            provider_failure(
                "XAI",
                response.status_code
            )

            return None

        data = request_json(
            response,
            "xAI"
        )

        if not data:
            return None

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            return None

        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )

        return clean_answer(
            content
        )

    except Exception as exc:

        print(
            "xAI ERROR:",
            exc
        )

        return None


# ============================================================
# POLLINATIONS - TEXT FALLBACK
# ============================================================

POLLINATIONS_API_KEY = os.getenv(
    "POLLINATIONS_API_KEY"
)

POLLINATIONS_CHAT_URL = (
    "https://gen.pollinations.ai/v1/chat/completions"
)

POLLINATIONS_TEXT_MODEL = os.getenv(
    "POLLINATIONS_TEXT_MODEL",
    "openai"
)


def ask_pollinations(message):

    if not POLLINATIONS_API_KEY:
        return None

    if not message:
        return None

    if not provider_available(
        "POLLINATIONS"
    ):
        return None

    try:

        print(
            "Trying fallback: Pollinations..."
        )

        response = requests.post(

            POLLINATIONS_CHAT_URL,

            headers={
                "Authorization":
                    f"Bearer {POLLINATIONS_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    POLLINATIONS_TEXT_MODEL,

                "messages": [

                    {
                        "role":
                            "user",

                        "content":
                            message
                    }
                ]
            },

            timeout=REQUEST_TIMEOUT
        )

        if response.status_code != 200:

            provider_failure(
                "POLLINATIONS",
                response.status_code
            )

            return None

        data = request_json(
            response,
            "Pollinations"
        )

        if not data:
            return None

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            return None

        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )

        return clean_answer(
            content
        )

    except Exception as exc:

        print(
            "Pollinations ERROR:",
            exc
        )

        return None


# ============================================================
# IMAGE GENERATION DETECTION
# ============================================================

IMAGE_WORDS = [

    "أنشئ صورة",
    "انشئ صورة",

    "أنشئ لي صورة",
    "انشئ لي صورة",

    "اصنع صورة",
    "اصنع لي صورة",

    "إنشاء صورة",
    "انشاء صورة",

    "ولد صورة",
    "ولّد صورة",

    "ارسم صورة",
    "ارسم لي",

    "صمم صورة",
    "صمم لي",

    "اعمل صورة",
    "اعمل لي صورة",

    "generate an image",
    "generate image",

    "create an image",
    "create image",

    "make an image",
    "make image",

    "draw an image",
    "draw image"
]


def is_image_generation_request(
    message
):

    if not message:
        return False

    text = str(
        message
    ).strip().lower()

    return any(
        word.lower() in text
        for word in IMAGE_WORDS
    )


# ============================================================
# EXTRACT IMAGE PROMPT
# ============================================================

def get_image_prompt(
    message
):

    if not message:
        return ""

    text = str(
        message
    ).strip()

    prefixes = [

        "أنشئ لي صورة",
        "أنشئ صورة",

        "انشئ لي صورة",
        "انشئ صورة",

        "اصنع لي صورة",
        "اصنع صورة",

        "إنشاء صورة",
        "انشاء صورة",

        "ولد صورة",
        "ولّد صورة",

        "ارسم لي",
        "ارسم صورة",

        "صمم لي صورة",
        "صمم صورة",

        "اعمل لي صورة",
        "اعمل صورة",

        "generate an image of",
        "generate image of",

        "create an image of",
        "create image of",

        "make an image of",
        "make image of",

        "draw an image of"
    ]

    lower = text.lower()

    for prefix in prefixes:

        if lower.startswith(
            prefix.lower()
        ):

            return text[
                len(prefix):
            ].strip()

    return text


# ============================================================
# IMAGE GENERATION
# ============================================================
#
# IMPORTANT:
# Groq itself does NOT expose an image-generation endpoint.
#
# Therefore Groq remains the primary AI that understands
# the user's request, but the actual image bytes must come
# from a real image-generation provider.
#
# This function uses xAI as the image generator if available.
#
# ============================================================

XAI_IMAGE_URL = (
    "https://api.x.ai/v1/images/generations"
)

XAI_IMAGE_MODEL = os.getenv(
    "XAI_IMAGE_MODEL",
    "grok-imagine-image-quality"
)


def generate_image_xai(
    prompt
):

    if not XAI_API_KEY:
        return None

    try:

        print(
            "IMAGE GENERATION:"
            " xAI"
        )

        response = requests.post(

            XAI_IMAGE_URL,

            headers={
                "Authorization":
                    f"Bearer {XAI_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    XAI_IMAGE_MODEL,

                "prompt":
                    prompt,

                "n":
                    1,

                "response_format":
                    "url"
            },

            timeout=REQUEST_TIMEOUT
        )

        print(
            "xAI IMAGE STATUS:",
            response.status_code
        )

        if response.status_code != 200:

            print(
                "xAI IMAGE RESPONSE:",
                response.text[:1500]
            )

            return None

        data = request_json(
            response,
            "xAI IMAGE"
        )

        if not data:
            return None

        items = data.get(
            "data",
            []
        )

        if not items:
            return None

        image_url = items[0].get(
            "url"
        )

        if image_url:

            print(
                "IMAGE GENERATION SUCCESS"
            )

            return image_url

        return None

    except Exception as exc:

        print(
            "xAI IMAGE ERROR:",
            exc
        )

        return None


# ============================================================
# IMAGE ROUTER
# ============================================================

def generate_image(
    prompt
):

    prompt = clean_answer(
        prompt
    )

    if not prompt:

        return {

            "answer":
                "اكتب وصف الصورة التي تريد إنشاءها.",

            "imageUrl":
                "",

            "provider":
                None
        }


    print(
        "=" * 60
    )

    print(
        "IMAGE REQUEST"
    )

    print(
        "GROQ = PRIMARY AI"
    )

    print(
        "IMAGE PROMPT:",
        prompt
    )

    print(
        "=" * 60
    )


    # --------------------------------------------------------
    # Groq first understands the request.
    # --------------------------------------------------------

    groq_understanding = ask_groq(

        f"""
The user wants an image.

Image description:
{prompt}

Return ONLY a concise, high-quality image-generation prompt.
Do not say that you cannot generate images.
Do not answer conversationally.
"""
    )


    final_prompt = (
        groq_understanding
        or prompt
    )


    print(
        "FINAL IMAGE PROMPT:",
        final_prompt
    )


    # --------------------------------------------------------
    # Actual image generation
    # --------------------------------------------------------

    image = generate_image_xai(
        final_prompt
    )

    if image:

        return {

            "answer":
                "تم إنشاء الصورة بنجاح.",

            "imageUrl":
                image,

            "provider":
                "xAI"
        }


    return {

        "answer":
            "فهمت طلب الصورة، "
            "لكن مولد الصور غير متاح حاليًا.",

        "imageUrl":
            "",

        "provider":
            None
    }


# ============================================================
# IMAGE VISION - GROQ PRIMARY
# ============================================================

def ask_groq_image(
    message,
    image_bytes,
    mime_type
):

    if not GROQ_API_KEY:
        return None

    if not image_bytes:
        return None

    if not provider_available(
        "GROQ_VISION"
    ):
        return None

    try:

        encoded = base64.b64encode(
            image_bytes
        ).decode(
            "utf-8"
        )

        image_url = (
            f"data:{mime_type};base64,"
            f"{encoded}"
        )

        print(
            "Trying PRIMARY VISION: Groq..."
        )

        response = requests.post(

            GROQ_URL,

            headers={
                "Authorization":
                    f"Bearer {GROQ_API_KEY}",

                "Content-Type":
                    "application/json"
            },

            json={

                "model":
                    GROQ_VISION_MODEL,

                "messages": [

                    {
                        "role":
                            "system",

                        "content":
                            """
You are Ido AI Vision.

Analyze the uploaded image carefully.

Answer the user's actual question.

If the user greets you and asks a question,
answer the question instead of returning
only a greeting.

Never claim that you created or modified the
image unless the application actually did so.
"""
                    },

                    {
                        "role":
                            "user",

                        "content": [

                            {
                                "type":
                                    "text",

                                "text":
                                    message
                            },

                            {
                                "type":
                                    "image_url",

                                "image_url": {

                                    "url":
                                        image_url
                                }
                            }
                        ]
                    }
                ],

                "temperature":
                    0.4,

                "max_completion_tokens":
                    2048
            },

            timeout=REQUEST_TIMEOUT
        )

        print(
            "Groq Vision Status:",
            response.status_code
        )

        if response.status_code != 200:

            print(
                "Groq Vision Response:",
                response.text[:1500]
            )

            provider_failure(
                "GROQ_VISION",
                response.status_code
            )

            return None

        data = request_json(
            response,
            "Groq Vision"
        )

        if not data:
            return None

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            return None

        content = (
            choices[0]
            .get(
                "message",
                {}
            )
            .get(
                "content"
            )
        )

        answer = clean_answer(
            content
        )

        if answer:

            print(
                "PRIMARY VISION SUCCESS: GROQ"
            )

            return answer

        return None

    except Exception as exc:

        print(
            "Groq Vision ERROR:",
            exc
        )

        return None


# ============================================================
# IMAGE RESPONSE ROUTER
# ============================================================

def get_image_response(
    message,
    image_bytes,
    mime_type,
    conversation_id=None
):

    if not image_bytes:

        return (
            "لم يتم إرسال صورة صالحة."
        )

    if not mime_type:

        mime_type = "image/jpeg"

    if not mime_type.startswith(
        "image/"
    ):

        return (
            "الملف المرسل ليس صورة صالحة."
        )

    if not message:

        message = (
            "حلل هذه الصورة واشرح لي "
            "ما الذي يظهر فيها."
        )

    message = str(
        message
    ).strip()


    # ========================================================
    # GROQ VISION = PRIMARY
    # ========================================================

    answer = ask_groq_image(

        message,

        image_bytes,

        mime_type
    )

    if answer:

        return answer


    # ========================================================
    # FALLBACK VISION
    # ========================================================
    #
    # OpenRouter / Mistral can be added here later.
    #
    # Groq remains FIRST.
    #
    # ========================================================

    return (
        "تعذر تحليل الصورة بواسطة Groq حاليًا."
    )


# ============================================================
# GREETING DETECTION
# ============================================================

GREETING_WORDS = [

    "السلام عليكم",
    "السلام عليكم ورحمة الله وبركاته",

    "مرحبا",
    "مرحبًا",

    "سلام",

    "hello",
    "hi",
    "hey"
]


def extract_greeting(
    message
):

    text = str(
        message
    ).strip()

    lower = text.lower()

    for greeting in GREETING_WORDS:

        if lower.startswith(
            greeting.lower()
        ):

            remainder = text[
                len(greeting):
            ].strip()

            return (
                greeting,
                remainder
            )

    return (
        None,
        text
    )


# ============================================================
# MAIN RESPONSE
# ============================================================

def get_response(
    message,
    conversation_id=None
):

    if not message:

        return (
            "اكتب رسالة أولًا."
        )

    original_message = str(
        message
    ).strip()

    if not original_message:

        return (
            "اكتب رسالة أولًا."
        )


    # ========================================================
    # IMAGE GENERATION
    # ========================================================

    if is_image_generation_request(
        original_message
    ):

        prompt = get_image_prompt(
            original_message
        )

        return generate_image(
            prompt
        )


    # ========================================================
    # GREETING + REAL QUESTION
    # ========================================================

    greeting, remainder = extract_greeting(
        original_message
    )

    if greeting and remainder:

        print(
            "GREETING + REAL REQUEST DETECTED"
        )

        # لا نعيد quick response.
        #
        # نرسل الطلب الحقيقي إلى Groq.
        #

        answer = ask_groq(
            remainder
        )

        if answer:

            if greeting.startswith(
                "السلام"
            ):

                return (
                    "وعليكم السلام ورحمة الله وبركاته.\n\n"
                    + answer
                )

            return (
                "مرحبًا بك.\n\n"
                + answer
            )


    # ========================================================
    # PRIMARY AI
    # ========================================================

    answer = ask_groq(
        original_message
    )

    if answer:

        print(
            "TEXT ROUTE SUCCESS: GROQ"
        )

        return answer


    # ========================================================
    # FALLBACKS
    # ========================================================

    fallback_routes = [

        (
            "MISTRAL",
            ask_mistral
        ),

        (
            "OPENROUTER",
            ask_openrouter
        ),

        (
            "XAI",
            ask_xai
        ),

        (
            "POLLINATIONS",
            ask_pollinations
        )
    ]


    for name, function in fallback_routes:

        if not provider_available(
            name
        ):

            print(
                f"{name}: SKIPPED"
            )

            continue

        try:

            answer = function(
                original_message
            )

        except Exception as exc:

            print(
                f"{name} ROUTER ERROR:",
                exc
            )

            answer = None

        if answer:

            print(
                f"TEXT FALLBACK SUCCESS: {name}"
            )

            return answer


    return (
        "أنا Ido AI، لكن لم أتمكن من "
        "الوصول إلى أي مزود ذكاء اصطناعي "
        "حاليًا."
    )


# ============================================================
# STARTUP
# ============================================================

print(
    "=" * 60
)

print(
    "IDO AI BRAIN.PY LOADED"
)

print(
    "PRIMARY AI:"
)

print(
    "    GROQ"
)

print(
    "TEXT ROUTE:"
)

print(
    "    GROQ -> MISTRAL -> OPENROUTER -> "
    "XAI -> POLLINATIONS"
)

print(
    "VISION ROUTE:"
)

print(
    "    GROQ VISION"
)

print(
    "IMAGE UNDERSTANDING:"
)

print(
    "    GROQ"
)

print(
    "IMAGE GENERATION:"
)

print(
    "    GROQ PROMPT UNDERSTANDING -> "
    "REAL IMAGE GENERATOR"
)

print(
    "GREETING:"
)

print(
    "    REAL REQUESTS ARE NOT REPLACED "
    "BY QUICK GREETINGS"
)

print(
    "=" * 60
)